### ISSUE TITLE
Hi! You do a great job. And I want to know that have you already released your Supp?Where could I get it? 

### ISSUE THREAD

**Issue by ZcsrenlongZ** [monakhova/starlight_denoising#1]

**Comment by zmlmanly** [comment]
I have the same problem.

**Comment by mldangelo** [comment]
I also have the same problem.

**Comment by monakhova** [comment]
I've added a link to the supplemental PDF on the project page. You can find it [here](https://kristinamonakhova.com/starlight_denoising/img/CVPR_2022_Starlight_Denoising_Supp.pdf).
In addition, the submission had two supplemental videos. These are already included on the project page as 'Denoised Submillilux videos' and 'Comparison against other methods'.
