### ISSUE TITLE
Raw Image Processing

### ISSUE THREAD

**Issue by gauenk** [monakhova/starlight_denoising#2]
I am wondering if you have the code used to process the raw images. I am trying to do the post-processing in Python, but I keep getting really purple and red scenes. I don't want to be pushy, but I am curious when this part will be released. Even a zip file for the code-base would be appreciated.

To elaborate, I would like to match the "post-processing example" from the flag video on the project page. I am processing the first 3 channels of frames 33 - 39 of sequence 21.

**Comment by gauenk** [comment]
Even just an ETA of seeing some code would be helpful! Thank you for considering :smile:

**Comment by monakhova** [comment]
Please stay tuned, the code will be up by the start of CVPR (June 19th). Thanks for your patience.

**Comment by gauenk** [comment]
This looks great -- thank you for such tidy code.
