### ISSUE TITLE
How you obtain the FPN

### ISSUE THREAD

**Issue by gravitychen** [monakhova/starlight_denoising#4]
Thank you for sharing your great work and great code!

I wonder how you obtain the [fixed_pattern_noise.mat](https://github.com/monakhova/starlight_denoising/blob/main/data/fixed_pattern_noise.mat) in /data directory.

**Comment by monakhova** [comment]
The fixed pattern noise is obtained experimentally from the camera. This is done by putting the lens cap on the camera, placing the camera in a dark room, and then taking a burst of images at the lowest exposure level of the camera. These images are then averaged together to obtain the fixed pattern noise.
