### ISSUE TITLE
preprocessing noisy_list

### ISSUE THREAD

**Issue by gravitychen** [monakhova/starlight_denoising#5]
And also I wonder how you preprocess the dng file, the "noisy_video" has the shape with [video_len,h,w,4].

and you try to visualize using 

```python
plt.imshow(noisy_video[ind][...,0:3]); 
```

Does this mean that the channel order is [R G B NIR], instead of [NIR R G B]

**Comment by monakhova** [comment]
That's right, the channel order is [R G B NIR]. In the example, we visualize only the RGB channels, which is why we select only the 1st 3 channels rather than all 4 channels.
